export const FETCH_CURRENCY_HISTORICAL_DATA = "FETCH_CURRENCY_HISTORICAL_DATA"
export const FETCH_CURRENCY_LATEST_DATA = "FETCH_CURRENCY_LATEST_DATA"

export const TOGGLE_CALCULATOR_MODAL = "TOGGLE_CALCULATOR_MODAL"

export const CHANGE_AUTO_CONVERTION_HISTORY_SAVE =
  "TOGGLE_AUTO_CONVERTION_HISTORY_SAVE"
export const CHANGE_AUTO_LOCATION = "TOGGLE_AUTO_LOCATION"
export const CHANGE_BASE_CURRENCY = "CHANGE_BASE_CURRENCY"
