export const FETCH_CURRENCY_HISTORICAL_DATA = "FETCH_CURRENCY_HISTORICAL_DATA"
export const FETCH_CURRENCY_LATEST_DATA = "FETCH_CURRENCY_LATEST_DATA"
export const TOGGLE_CALCULATOR_MODAL = "TOGGLE_CALCULATOR_MODAL"
