# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'cc_project' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for cc_project
# Required by RNFirebase
pod 'Firebase/Core'
pod 'Firebase/Database'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

  target 'cc_projectTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'cc_project-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for cc_project-tvOS

  target 'cc_project-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
